import ast
from .feature_extraction import extract_features
from .ml_model import your_ml_model_module

def detect_ai_generated_code(source_code_file):
    """
    Detects whether the code in the specified file was generated by an AI bot.

    Args:
        source_code_file: The path to the source code file to analyze.

    Returns:
        A boolean value indicating whether the code was generated by an AI bot.
    """
    # Parse the source code
    with open(source_code_file, "r") as f:
        code = f.read()
    parsed_code = ast.parse(code)

    # Extract features from the source code
    features = extract_features(parsed_code)

    # Make a prediction using the machine learning model
    prediction = your_ml_model_module.predict(features)

    return prediction

if __name__ == "__main__":
    source_code_file = "path/to/source/code/file"
    prediction = detect_ai_generated_code(source_code_file)
    if prediction:
        print("AI-generated code")
    else:
        print("Human-written code")
